### ISSUE TITLE
Catbox-moe.upload() isn't a function

### ISSUE THREAD

**Issue by filiptronicek** [tentaclenotsoft/node-catbox#1]
When trying to access the upload function as in the documentation, this code throws an error
```js
const cat = require("catbox.moe");
cat.upload("https://files.catbox.moe/imhw87.png");
```
```
TypeError: cat.upload is not a function
    at Object.<anonymous> (D:\Documents\Coading\interclip_upload\index.js:2:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by samueldurantes** [comment]
This is a promise, you need to solve it...

**Comment by ruj** [comment]
`cat` is a [constructor](https://github.com/tenasatupitsyn/node-catbox#constructoruserhash)
In it you can pass your user hash

**Comment by filiptronicek** [comment]
Then wouldn’t it be nice to have some starter code for people that aren’t that familiar with constructors in the README?

**Comment by ruj** [comment]
In version [0.1.5](https://www.npmjs.com/package/catbox.moe/v/0.1.5) was better expressed how to take care of the [constructor](https://github.com/tenasatupitsyn/node-catbox#catboxuserhash), this is brief until the new version.
